-- Disposable transaction; verify quotas, live plans, payment lifecycle and denial.
begin;
create function pg_temp.check_plan(ok boolean,message text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception '%',message; end if; end $$;
do $$
declare owner_id uuid:=gen_random_uuid(); member_id uuid:=gen_random_uuid(); other_id uuid:=gen_random_uuid(); project_id uuid; extra_id uuid; request_id uuid; job_id uuid; before_bytes bigint; expiry timestamptz; blocked boolean:=false;
begin
 insert into auth.users(id,email,email_confirmed_at) values(owner_id,'e2e-plan-owner@roleway.test',now()),(member_id,'e2e-plan-member@roleway.test',now()),(other_id,'e2e-plan-other@roleway.test',now());
 insert into public.admin_members(user_id,role) values(owner_id,'owner') on conflict(user_id) do update set role='owner';
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 select active_project_id into project_id from public.profiles where user_id=member_id;
 perform pg_temp.check_plan((select active_workspaces=1 from public.account_usage where user_id=member_id),'Initial Workspace was not metered');
 begin insert into public.search_projects(user_id,name) values(member_id,'Over free limit'); exception when others then blocked:=sqlerrm='PLAN_WORKSPACE_LIMIT'; end;
 perform pg_temp.check_plan(blocked,'Free Workspace limit not enforced'); blocked:=false;
 begin perform public.admin_save_plan('free','Free','',0,'PHP','available',10,10485760); exception when others then blocked:=true; end;
 perform pg_temp.check_plan(blocked,'Member changed plans');blocked:=false;
 begin perform public.admin_user_detail(other_id); exception when others then blocked:=true; end;
 perform pg_temp.check_plan(blocked,'Member inspected another account');blocked:=false;
 begin perform public.request_plan_payment('plus');exception when others then blocked:=true;end;
 perform pg_temp.check_plan(blocked,'Coming-soon plan accepted payment');blocked:=false;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 perform public.admin_save_plan('plus','Plus','Several searches',14900,'PHP','available',5,104857600);
 perform public.admin_save_billing(true,'Test bank','Fixture beneficiary','123','Include request ID','','support@example.test');
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 request_id:=public.request_plan_payment('plus');
 begin perform public.request_plan_payment('plus');exception when unique_violation then blocked:=true;end;
 perform pg_temp.check_plan(blocked,'Duplicate open request accepted');blocked:=false;
 perform set_config('request.jwt.claim.sub',other_id::text,true);
 begin perform public.submit_plan_payment(request_id,'OTHER-REF');exception when others then blocked:=true;end;
 perform pg_temp.check_plan(blocked,'Another member submitted a request');blocked:=false;
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 perform public.submit_plan_payment(request_id,'BANK-123');
 perform pg_temp.check_plan((public.effective_plan(member_id)).slug='free','Unverified reference granted paid access');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 perform public.admin_save_plan('plus','Plus','Several searches',19900,'PHP','available',5,104857600);
 perform pg_temp.check_plan((select amount_minor=14900 from public.payment_requests where id=request_id),'Request price changed with catalog');
 perform public.admin_review_payment(request_id,true,'Verified full transfer in bank');
 select expires_at into expiry from public.account_plans where user_id=member_id;
 perform pg_temp.check_plan((public.effective_plan(member_id)).slug='plus','Approval did not grant plan');
 begin perform public.admin_review_payment(request_id,true,'Duplicate');exception when others then blocked:=true;end;
 perform pg_temp.check_plan(blocked,'Duplicate approval accepted');blocked:=false;
 perform pg_temp.check_plan((select expires_at=expiry from public.account_plans where user_id=member_id),'Duplicate review extended plan');
 insert into public.search_projects(user_id,name) values(member_id,'Second search') returning id into extra_id;
 perform public.admin_assign_plan(member_id,'free',null,'Test downgrade preserving content');
 perform pg_temp.check_plan((select count(*)=2 from public.search_projects where user_id=member_id),'Downgrade deleted records');
 update public.search_projects set status='archived' where id=extra_id;
 perform pg_temp.check_plan((select active_workspaces=1 from public.account_usage where user_id=member_id),'Archive did not release slot');
 begin update public.search_projects set status='active' where id=extra_id;exception when others then blocked:=sqlerrm='PLAN_WORKSPACE_LIMIT';end;
 perform pg_temp.check_plan(blocked,'Restore bypassed quota');blocked:=false;
 insert into public.jobs(user_id,project_id,company,title,description) values(member_id,project_id,'Fixture','Engineer','hello') returning id into job_id;
 select content_bytes into before_bytes from public.account_usage where user_id=member_id;
 begin update public.jobs set description=repeat('x',10485760) where id=job_id;exception when others then blocked:=sqlerrm='PLAN_STORAGE_LIMIT';end;
 perform pg_temp.check_plan(blocked,'Storage growth bypassed limit');blocked:=false;
 perform pg_temp.check_plan((select content_bytes=before_bytes from public.account_usage where user_id=member_id),'Failed growth changed usage');
 perform pg_temp.check_plan((public.admin_user_detail(member_id,'jobs',job_id)->'record'->>'description')='hello','Content inspection did not return exact record');
 delete from public.jobs where id=job_id;
 perform pg_temp.check_plan((select content_bytes<before_bytes from public.account_usage where user_id=member_id),'Delete did not release bytes');
 begin update public.search_projects set status='archived',target_titles=array[repeat('x',10485760)] where id=project_id;exception when others then blocked:=sqlerrm='PLAN_STORAGE_LIMIT';end;
 perform pg_temp.check_plan(blocked,'Archiving allowed arbitrary storage growth');blocked:=false;
 insert into public.jobs(user_id,project_id,company,title,description) values(member_id,project_id,'Fixture','Existing large content',repeat('x',1048576)) returning id into job_id;
 perform public.admin_save_plan('free','Free','',0,'PHP','available',1,1048576);
 update public.search_projects set status='archived' where id=project_id;
 perform pg_temp.check_plan((select active_workspaces=0 from public.account_usage where user_id=member_id),'Over-storage account could not archive');
 delete from public.jobs where id=job_id;
 perform public.admin_assign_plan(member_id,'pro',now()+interval '1 day','Test expiry');
 update public.account_plans set expires_at=now()-interval '1 second' where user_id=member_id;
 perform pg_temp.check_plan((public.effective_plan(member_id)).slug='free','Expired plan remained active');
 delete from auth.users where id=member_id;
 perform pg_temp.check_plan(not exists(select 1 from public.account_usage where user_id=member_id),'Account deletion left usage');
end $$;
rollback;

begin;
insert into auth.users(id,email,email_confirmed_at) values('adad0000-0000-4000-8000-000000000001','e2e-rls-one@roleway.test',now()),('adad0000-0000-4000-8000-000000000002','e2e-rls-two@roleway.test',now());
insert into public.account_plans(user_id,plan_slug) values('adad0000-0000-4000-8000-000000000001','free'),('adad0000-0000-4000-8000-000000000002','free');
set local role authenticated;
select set_config('request.jwt.claim.sub','adad0000-0000-4000-8000-000000000001',true);
do $$ declare denied boolean:=false; begin
 if (select count(*) from public.account_plans)<>1 then raise exception 'Cross-account plan disclosure';end if;
 if (select count(*) from public.account_usage)<>1 then raise exception 'Cross-account usage disclosure';end if;
 begin update public.account_usage set content_bytes=0;exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Member can rewrite quota ledger';end if;
end $$;
reset role;
rollback;
