import { CheckCircle2, KeyRound, PlugZap, ShieldCheck, Trash2, TriangleAlert } from "lucide-react";
import { AiConnectionForm } from "@/components/ai-connection-form";
import { SettingsNav } from "@/components/settings-nav";
import { SubmitButton } from "@/components/submit-button";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireUser } from "@/lib/supabase/server";
import { deleteAiConnection, testAiConnection } from "./actions";

export default async function AiSettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string; tested?: string; deleted?: string; error?: string }> }) {
  const [auth, query] = await Promise.all([requireUser(), searchParams]); if (!auth) return null;
  const { data: connections } = await createAdminClient().from("ai_connections").select("id, provider, label, model, base_url, key_hint, status, last_error, last_tested_at").eq("user_id", auth.user.id).order("updated_at", { ascending: false });
  return <div className="page settings-page"><header className="page-header"><div><h1>Settings</h1><p className="page-subtitle">Tune Roleway around the way you work.</p></div></header><div className="settings-layout"><SettingsNav active="AI connections" /><main>{query.saved ? <div className="form-alert success" role="status">AI connection saved. Test it before the first run.</div> : null}{query.tested ? <div className="form-alert success" role="status">Connection verified and ready.</div> : null}{query.deleted ? <div className="form-alert success" role="status">Connection removed.</div> : null}{query.error ? <div className="form-alert error" role="alert">{query.error}</div> : null}<section className="form-section"><div className="settings-section-title"><span className="settings-section-icon"><KeyRound aria-hidden="true" /></span><div><h2>Provider connections</h2><p>Connect a provider account for optional, on-demand assistance.</p></div></div><div className="ai-safety-note"><ShieldCheck aria-hidden="true" /><p><strong>AI stays an extension.</strong> Core tracking works without it. Roleway sends context only when you start a run, shows the result as a draft, and never submits an application or contacts anyone.</p></div>{connections?.length ? <div className="connection-list">{connections.map((connection) => <article className="connection-row" key={connection.id}><span className={`connection-status ${connection.status}`} aria-hidden="true">{connection.status === "connected" ? <CheckCircle2 /> : connection.status === "error" ? <TriangleAlert /> : <PlugZap />}</span><div className="connection-copy"><strong>{connection.label}</strong><span>{providerLabel(connection.provider)} · <span className="mono">{connection.model}</span> · {connection.key_hint}</span>{connection.last_error ? <small>{connection.last_error}</small> : null}</div><span className={`status-label ${connection.status === "connected" ? "success" : "neutral"}`}><i />{connection.status}</span><form action={testAiConnection}><input type="hidden" name="connectionId" value={connection.id} /><SubmitButton className="button secondary" pendingLabel="Testing…">Test</SubmitButton></form><form action={deleteAiConnection}><input type="hidden" name="connectionId" value={connection.id} /><SubmitButton className="icon-button" pendingLabel="…" ariaLabel={`Delete ${connection.label}`}><Trash2 aria-hidden="true" /></SubmitButton></form></article>)}</div> : <div className="empty-inline">No provider connected yet.</div>}</section><section className="form-section"><h2>Add a connection</h2><p>Your provider bills API usage directly. A ChatGPT, Claude, or Gemini consumer subscription does not automatically include API usage; create an API key in the provider’s developer console.</p><AiConnectionForm /></section></main></div></div>;
}

function providerLabel(provider: string) {
  return ({ openai: "OpenAI", anthropic: "Anthropic", gemini: "Google Gemini", openrouter: "OpenRouter", "openai-compatible": "Compatible API" } as Record<string, string>)[provider] || provider;
}
