import { FileText, Plus } from "lucide-react";
import { createDocument } from "@/features/workspace/actions";
import { requireUser } from "@/lib/supabase/server";

export default async function DocumentsPage() {
  const auth = await requireUser();
  if (!auth) return null;
  const { data: documents, error } = await auth.supabase.from("documents").select("id, title, kind, status, updated_at, opportunities(reference_number, jobs(company, title))").order("updated_at", { ascending: false });
  return <div className="page narrow"><header className="page-header"><div className="page-header-copy"><h1>Documents</h1><p className="page-subtitle">Focused application material with clear ownership and status.</p></div></header><section className="inline-create compact-form"><div><h2>Create a document</h2><p className="page-subtitle">Start a focused draft—not a generic blank document.</p></div><form action={createDocument} className="quick-add"><input className="input" name="title" required placeholder="Document title" /><select className="input" name="kind" defaultValue="resume"><option value="resume">Resume</option><option value="cover_letter">Cover letter</option><option value="answer">Application answer</option><option value="message">Message</option><option value="research_note">Research note</option><option value="interview_note">Interview note</option></select><button className="button primary"><Plus />Create</button></form></section>{error ? <div className="form-alert error">Documents could not be loaded.</div> : null}{!error && documents?.length === 0 ? <div className="empty-state"><span className="empty-icon"><FileText /></span><h2>No documents yet</h2><p>Create a resume, answer, or message when an opportunity needs it. Versions and content editing will stay attached here.</p></div> : null}{documents && documents.length > 0 ? <section className="document-list">{documents.map((document) => <article className="list-row" key={document.id}><span className="list-icon"><FileText /></span><div><div className="list-title">{document.title}</div><div className="list-subtitle">{document.kind.replaceAll("_", " ")}</div></div><span className="tag">{document.status}</span><time className="muted small">{new Date(document.updated_at).toLocaleDateString()}</time><span /></article>)}</section> : null}</div>;
}
