import { FileText, Plus } from "lucide-react";
import Link from "next/link";
import { createDocument } from "@/features/workspace/actions";
import { requireUser } from "@/lib/supabase/server";
import { SubmitButton } from "@/components/submit-button";

export default async function DocumentsPage({ searchParams }: { searchParams: Promise<{ error?: string; deleted?: string }> }) {
  const [auth, query] = await Promise.all([requireUser(), searchParams]);
  if (!auth) return null;
  const { data: documents, error } = await auth.supabase.from("documents").select("id, title, kind, status, updated_at, opportunities(reference_number, jobs(company, title))").order("updated_at", { ascending: false });
  return <div className="page narrow"><header className="page-header"><div className="page-header-copy"><h1>Documents</h1><p className="page-subtitle">Focused application material with clear ownership and status.</p></div></header>{query.error ? <div className="form-alert error" role="alert">{query.error}</div> : null}{query.deleted ? <div className="form-alert success" role="status">Document deleted.</div> : null}<section className="inline-create compact-form"><div><h2>Create a document</h2><p className="page-subtitle">Start a focused draft and attach it to an Opportunity when it is ready.</p></div><form action={createDocument} className="quick-add"><label className="sr-only" htmlFor="document-title">Document title</label><input className="input" id="document-title" name="title" required placeholder="Document title…" autoComplete="off" /><label className="sr-only" htmlFor="document-kind">Document type</label><select className="input" id="document-kind" name="kind" defaultValue="resume"><option value="resume">Resume</option><option value="cover_letter">Cover letter</option><option value="answer">Application answer</option><option value="message">Message</option><option value="research_note">Research note</option><option value="interview_note">Interview note</option></select><SubmitButton pendingLabel="Creating…"><Plus />Create</SubmitButton></form></section>{error ? <div className="empty-state"><h2>Documents could not be loaded</h2><p>Check your connection and refresh this page.</p></div> : null}{!error && documents?.length === 0 ? <div className="empty-state"><span className="empty-icon"><FileText /></span><h2>No documents yet</h2><p>Create a resume, answer, message, or note when an Opportunity needs it.</p></div> : null}{documents && documents.length > 0 ? <section className="document-list" aria-label="Documents">{documents.map((document) => <Link className="list-row list-row-link" href={`/documents/${document.id}`} key={document.id}><span className="list-icon"><FileText aria-hidden="true" /></span><div><div className="list-title">{document.title}</div><div className="list-subtitle">{document.kind.replaceAll("_", " ")}</div></div><span className="tag">{document.status}</span><time className="muted small">{new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" }).format(new Date(document.updated_at))}</time><span aria-hidden="true">→</span></Link>)}</section> : null}</div>;
}
