import { SettingsNav } from "@/components/settings-nav";
import { requireUser } from "@/lib/supabase/server";
import { updatePreferences } from "../actions";

export default async function PreferencesPage() {
  const auth = await requireUser(); if (!auth) return null;
  const { data: preferences } = await auth.supabase.from("career_preferences").select("target_titles, preferred_technologies, remote_preference, allowed_locations, minimum_compensation, excluded_criteria").eq("user_id", auth.user.id).maybeSingle();
  return <div className="page"><header className="page-header"><div><h1>Settings</h1><p className="page-subtitle">Define what a good opportunity means for you.</p></div></header><div className="settings-layout"><SettingsNav active="Job preferences" /><main><form action={updatePreferences} className="form-section"><h2>Job preferences</h2><p>Separate multiple values with commas. These remain private in your Supabase workspace.</p><div className="field"><label htmlFor="targetTitles">Target roles</label><input className="input" id="targetTitles" name="targetTitles" defaultValue={preferences?.target_titles?.join(", ") ?? ""} /></div><div className="field"><label htmlFor="technologies">Preferred technologies</label><input className="input" id="technologies" name="technologies" defaultValue={preferences?.preferred_technologies?.join(", ") ?? ""} /></div><div className="field-grid"><div className="field"><label htmlFor="remotePreference">Remote preference</label><select className="input" id="remotePreference" name="remotePreference" defaultValue={preferences?.remote_preference ?? "flexible"}><option value="required">Required</option><option value="preferred">Preferred</option><option value="flexible">Flexible</option></select></div><div className="field"><label htmlFor="minimumCompensation">Minimum compensation</label><input className="input" id="minimumCompensation" name="minimumCompensation" type="number" min="0" defaultValue={preferences?.minimum_compensation ?? ""} /></div></div><div className="field"><label htmlFor="locations">Allowed locations</label><input className="input" id="locations" name="locations" defaultValue={preferences?.allowed_locations?.join(", ") ?? ""} /></div><div className="field"><label htmlFor="excludedCriteria">Avoid</label><textarea className="textarea" id="excludedCriteria" name="excludedCriteria" defaultValue={preferences?.excluded_criteria?.join(", ") ?? ""} /></div><button className="button primary">Save preferences</button></form></main></div></div>;
}
