import { boolean, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

const id = () => uuid("id").primaryKey().defaultRandom();
const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const ownerId = () => uuid("user_id").notNull();
export const users = pgTable("users", { id: uuid("id").primaryKey(), email: text("email").notNull(), createdAt: createdAt() });
export const profiles = pgTable("profiles", { id: id(), userId: ownerId(), headline: text("headline"), summary: text("summary"), details: jsonb("details").notNull().default({}), createdAt: createdAt() }, (t) => [uniqueIndex("profiles_user_uidx").on(t.userId)]);
export const careerPreferences = pgTable("career_preferences", { id: id(), userId: ownerId(), preferences: jsonb("preferences").notNull().default({}), createdAt: createdAt() }, (t) => [uniqueIndex("preferences_user_uidx").on(t.userId)]);

export const experiences = pgTable("experiences", { id: id(), userId: ownerId(), company: text("company").notNull(), title: text("title").notNull(), content: jsonb("content").notNull(), approved: boolean("approved").notNull().default(false), createdAt: createdAt() }, (t) => [index("experiences_owner_idx").on(t.userId, t.createdAt)]);
export const projects = pgTable("projects", { id: id(), userId: ownerId(), name: text("name").notNull(), content: jsonb("content").notNull(), approved: boolean("approved").notNull().default(false), createdAt: createdAt() }, (t) => [index("projects_owner_idx").on(t.userId, t.createdAt)]);
export const skills = pgTable("skills", { id: id(), userId: ownerId(), name: text("name").notNull(), years: integer("years"), approved: boolean("approved").notNull().default(false), createdAt: createdAt() }, (t) => [uniqueIndex("skills_owner_name_uidx").on(t.userId, t.name)]);
export const education = pgTable("education", { id: id(), userId: ownerId(), institution: text("institution").notNull(), content: jsonb("content").notNull(), approved: boolean("approved").notNull().default(false), createdAt: createdAt() });
export const certifications = pgTable("certifications", { id: id(), userId: ownerId(), name: text("name").notNull(), content: jsonb("content").notNull(), approved: boolean("approved").notNull().default(false), createdAt: createdAt() });
export const achievements = pgTable("achievements", { id: id(), userId: ownerId(), title: text("title").notNull(), content: jsonb("content").notNull(), approved: boolean("approved").notNull().default(false), createdAt: createdAt() });

export const jobSources = pgTable("job_sources", { id: id(), userId: ownerId(), kind: text("kind").notNull(), externalId: text("external_id"), url: text("url"), createdAt: createdAt() });
export const jobs = pgTable("jobs", { id: id(), userId: ownerId(), sourceId: uuid("source_id"), company: text("company").notNull(), title: text("title").notNull(), location: text("location"), compensation: text("compensation"), inboxState: text("inbox_state").notNull().default("new"), createdAt: createdAt() }, (t) => [index("jobs_owner_created_idx").on(t.userId, t.createdAt)]);
export const jobSnapshots = pgTable("job_snapshots", { id: id(), userId: ownerId(), jobId: uuid("job_id").notNull(), rawContent: text("raw_content").notNull(), normalized: jsonb("normalized").notNull(), retrievedAt: timestamp("retrieved_at", { withTimezone: true }).notNull(), createdAt: createdAt() }, (t) => [index("job_snapshots_job_idx").on(t.jobId, t.retrievedAt)]);
export const jobRequirements = pgTable("job_requirements", { id: id(), userId: ownerId(), snapshotId: uuid("snapshot_id").notNull(), requirement: text("requirement").notNull(), importance: text("importance").notNull(), match: text("match"), evidenceIds: jsonb("evidence_ids").notNull().default([]), createdAt: createdAt() });

export const opportunityStages = pgTable("opportunity_stages", { id: id(), userId: ownerId(), key: text("key").notNull(), label: text("label").notNull(), position: integer("position").notNull(), terminal: boolean("terminal").notNull().default(false), createdAt: createdAt() }, (t) => [uniqueIndex("stages_owner_key_uidx").on(t.userId, t.key)]);
export const opportunities = pgTable("opportunities", { id: id(), userId: ownerId(), jobId: uuid("job_id").notNull(), stage: text("stage").notNull(), nextAction: text("next_action"), nextActionDueAt: timestamp("next_action_due_at", { withTimezone: true }), closedReason: text("closed_reason"), fitAnalysis: jsonb("fit_analysis"), createdAt: createdAt() }, (t) => [uniqueIndex("opportunities_owner_job_uidx").on(t.userId, t.jobId), index("opportunities_owner_stage_idx").on(t.userId, t.stage)]);
export const opportunityEvents = pgTable("opportunity_events", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id").notNull(), actor: text("actor").notNull(), type: text("type").notNull(), payload: jsonb("payload").notNull().default({}), createdAt: createdAt() }, (t) => [index("opportunity_events_timeline_idx").on(t.opportunityId, t.createdAt)]);
export const opportunityNotes = pgTable("opportunity_notes", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id").notNull(), body: text("body").notNull(), createdAt: createdAt() });
export const tasks = pgTable("tasks", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id"), title: text("title").notNull(), category: text("category").notNull(), status: text("status").notNull(), priority: text("priority").notNull(), dueAt: timestamp("due_at", { withTimezone: true }), createdBy: text("created_by").notNull(), createdAt: createdAt() }, (t) => [index("tasks_owner_due_idx").on(t.userId, t.status, t.dueAt)]);

export const resumeBases = pgTable("resume_bases", { id: id(), userId: ownerId(), name: text("name").notNull(), content: jsonb("content").notNull(), createdAt: createdAt() });
export const resumeVersions = pgTable("resume_versions", { id: id(), userId: ownerId(), baseId: uuid("base_id").notNull(), opportunityId: uuid("opportunity_id"), version: integer("version").notNull(), status: text("status").notNull(), content: jsonb("content").notNull(), parentId: uuid("parent_id"), createdAt: createdAt() }, (t) => [uniqueIndex("resume_version_uidx").on(t.baseId, t.opportunityId, t.version)]);
export const resumeSections = pgTable("resume_sections", { id: id(), userId: ownerId(), resumeVersionId: uuid("resume_version_id").notNull(), kind: text("kind").notNull(), position: integer("position").notNull(), content: jsonb("content").notNull(), createdAt: createdAt() });
export const documents = pgTable("documents", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id"), kind: text("kind").notNull(), title: text("title").notNull(), status: text("status").notNull(), createdAt: createdAt() });
export const documentVersions = pgTable("document_versions", { id: id(), userId: ownerId(), documentId: uuid("document_id").notNull(), version: integer("version").notNull(), content: jsonb("content").notNull(), createdAt: createdAt() }, (t) => [uniqueIndex("document_version_uidx").on(t.documentId, t.version)]);
export const applicationRecords = pgTable("application_records", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id").notNull(), submittedAt: timestamp("submitted_at", { withTimezone: true }), resumeVersionId: uuid("resume_version_id"), followUpAt: timestamp("follow_up_at", { withTimezone: true }), details: jsonb("details").notNull().default({}), createdAt: createdAt() });
export const applicationAnswers = pgTable("application_answers", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id"), category: text("category").notNull(), canonical: text("canonical").notNull(), variants: jsonb("variants").notNull().default([]), evidenceIds: jsonb("evidence_ids").notNull().default([]), createdAt: createdAt() });

export const contacts = pgTable("contacts", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id"), name: text("name").notNull(), role: text("role"), relationshipType: text("relationship_type").notNull(), details: jsonb("details").notNull().default({}), followUpAt: timestamp("follow_up_at", { withTimezone: true }), createdAt: createdAt() });
export const contactEvents = pgTable("contact_events", { id: id(), userId: ownerId(), contactId: uuid("contact_id").notNull(), type: text("type").notNull(), details: jsonb("details").notNull().default({}), createdAt: createdAt() });
export const interviews = pgTable("interviews", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id").notNull(), type: text("type").notNull(), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), durationMinutes: integer("duration_minutes"), details: jsonb("details").notNull().default({}), outcome: text("outcome"), createdAt: createdAt() }, (t) => [index("interviews_owner_starts_idx").on(t.userId, t.startsAt)]);
export const interviewSessions = pgTable("interview_sessions", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id"), mode: text("mode").notNull(), status: text("status").notNull(), review: jsonb("review"), createdAt: createdAt() });
export const questions = pgTable("questions", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id"), category: text("category").notNull(), prompt: text("prompt").notNull(), difficulty: text("difficulty"), tags: jsonb("tags").notNull().default([]), createdAt: createdAt() });
export const practiceAnswers = pgTable("practice_answers", { id: id(), userId: ownerId(), questionId: uuid("question_id").notNull(), sessionId: uuid("session_id"), answer: text("answer").notNull(), feedback: jsonb("feedback"), confidence: integer("confidence"), createdAt: createdAt() });

export const researchItems = pgTable("research_items", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id").notNull(), kind: text("kind").notNull(), content: text("content").notNull(), freshness: timestamp("freshness", { withTimezone: true }).notNull(), createdAt: createdAt() });
export const researchSources = pgTable("research_sources", { id: id(), userId: ownerId(), researchItemId: uuid("research_item_id").notNull(), title: text("title").notNull(), url: text("url").notNull(), retrievedAt: timestamp("retrieved_at", { withTimezone: true }).notNull(), createdAt: createdAt() });
export const notifications = pgTable("notifications", { id: id(), userId: ownerId(), type: text("type").notNull(), title: text("title").notNull(), readAt: timestamp("read_at", { withTimezone: true }), payload: jsonb("payload").notNull().default({}), createdAt: createdAt() }, (t) => [index("notifications_owner_read_idx").on(t.userId, t.readAt)]);

export const aiProviders = pgTable("ai_providers", { id: id(), userId: ownerId(), kind: text("kind").notNull(), name: text("name").notNull(), endpoint: text("endpoint"), enabled: boolean("enabled").notNull().default(true), createdAt: createdAt() });
export const aiConfigs = pgTable("ai_configs", { id: id(), userId: ownerId(), providerId: uuid("provider_id").notNull(), encryptedCredential: text("encrypted_credential"), models: jsonb("models").notNull().default({}), createdAt: createdAt() }, (t) => [uniqueIndex("ai_configs_provider_uidx").on(t.userId, t.providerId)]);
export const agentThreads = pgTable("agent_threads", { id: id(), userId: ownerId(), opportunityId: uuid("opportunity_id"), title: text("title").notNull(), createdAt: createdAt() });
export const agentMessages = pgTable("agent_messages", { id: id(), userId: ownerId(), threadId: uuid("thread_id").notNull(), role: text("role").notNull(), content: jsonb("content").notNull(), createdAt: createdAt() });
export const agentRuns = pgTable("agent_runs", { id: id(), userId: ownerId(), threadId: uuid("thread_id"), opportunityId: uuid("opportunity_id"), kind: text("kind").notNull(), status: text("status").notNull(), provider: text("provider"), model: text("model"), contextManifest: jsonb("context_manifest").notNull(), usage: jsonb("usage"), error: jsonb("error"), createdAt: createdAt() }, (t) => [index("agent_runs_owner_created_idx").on(t.userId, t.createdAt)]);
export const agentSteps = pgTable("agent_steps", { id: id(), userId: ownerId(), runId: uuid("run_id").notNull(), position: integer("position").notNull(), label: text("label").notNull(), status: text("status").notNull(), details: jsonb("details"), createdAt: createdAt() });
export const toolCalls = pgTable("tool_calls", { id: id(), userId: ownerId(), runId: uuid("run_id").notNull(), tool: text("tool").notNull(), permission: text("permission").notNull(), input: jsonb("input").notNull(), output: jsonb("output"), createdAt: createdAt() });
export const approvals = pgTable("approvals", { id: id(), userId: ownerId(), runId: uuid("run_id").notNull(), toolCallId: uuid("tool_call_id"), status: text("status").notNull(), proposal: jsonb("proposal").notNull(), decidedAt: timestamp("decided_at", { withTimezone: true }), createdAt: createdAt() }, (t) => [index("approvals_owner_status_idx").on(t.userId, t.status)]);
