import { signOut } from "@/app/auth/actions";
import { deleteAccount } from "@/app/(app)/settings/actions";
import { SettingsNav } from "@/components/settings-nav";
import { SubmitButton } from "@/components/submit-button";
import { requireUser } from "@/lib/supabase/server";

export default async function PrivacyPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const [auth, query] = await Promise.all([requireUser(), searchParams]); if (!auth) return null;
  return <div className="page"><header className="page-header"><div><h1>Settings</h1><p className="page-subtitle">Control your account, workspace data, and active session.</p></div></header><div className="settings-layout"><SettingsNav active="Privacy & data" /><main>{query.error ? <div className="form-alert error" role="alert">{query.error}</div> : null}<section className="form-section"><h2>Supabase workspace</h2><p>Your profile, preferences, Jobs, Opportunities, tasks, notes, interviews, and documents are stored in Supabase PostgreSQL. Row-level security restricts every record to the authenticated owner.</p><div className="detail-row"><dt>Signed in as</dt><dd>{auth.user.email}</dd></div><div className="detail-row"><dt>Authentication</dt><dd>Email and password via Supabase Auth</dd></div></section><section className="form-section"><h2>Export workspace</h2><p>Download a JSON archive of your Roleway profile and workspace records. The export is generated on demand and is not cached.</p><a className="button secondary" href="/api/export" download>Download data export</a></section><section className="form-section"><h2>Session</h2><p>Signing out clears the current browser session. Your workspace remains available the next time you sign in.</p><form action={signOut}><SubmitButton className="button secondary" pendingLabel="Signing out…">Sign out</SubmitButton></form></section><section className="form-section danger-zone"><h2>Delete account</h2><p>Permanently delete your account and all owner-scoped workspace records. This cannot be undone.</p><form action={deleteAccount} className="delete-account-form"><div className="field"><label htmlFor="confirmation">Type <strong>DELETE</strong> to confirm</label><input className="input" id="confirmation" name="confirmation" autoComplete="off" required pattern="DELETE" /></div><SubmitButton className="button danger" pendingLabel="Deleting account…">Delete account permanently</SubmitButton></form></section></main></div></div>;
}
