import { restartTour } from "@/app/(app)/tour-actions";
import { SettingsNav } from "@/components/settings-nav";
import { SubmitButton } from "@/components/submit-button";
import { requireUser } from "@/lib/supabase/server";
import { updateProfile } from "../actions";

export default async function ProfilePage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [auth, query] = await Promise.all([requireUser(), searchParams]); if (!auth) return null;
  const { data: profile, error } = await auth.supabase.from("profiles").select("full_name, headline, summary").eq("user_id", auth.user.id).single();
  const initials = String(profile?.full_name || auth.user.email || "R").split(/[\s@]+/).map((part: string) => part[0]).join("").slice(0, 2).toUpperCase();
  return <div className="page settings-page"><header className="page-header"><div><h1>Settings</h1><p className="page-subtitle">Tune Roleway around the way you work.</p></div></header><div className="settings-layout"><SettingsNav active="Profile" /><main>{query.saved ? <div className="form-alert success" role="status">Profile saved.</div> : null}{query.error ? <div className="form-alert error" role="alert">{query.error}</div> : null}{error || !profile ? <div className="form-alert error">Your profile could not be loaded.</div> : <form action={updateProfile}><section className="form-section"><div className="profile-identity"><span className="avatar avatar-large">{initials}</span><div><h2>Profile</h2><p>{auth.user.email}</p></div></div><p>This is your career source of truth. Keep it factual and current so every Opportunity starts with the right context.</p><div className="field"><label htmlFor="fullName">Full name</label><input id="fullName" name="fullName" className="input" required defaultValue={profile.full_name} autoComplete="name" /></div><div className="field"><label htmlFor="headline">Professional headline</label><input id="headline" name="headline" className="input" defaultValue={profile.headline} placeholder="Product engineer focused on dependable systems" /><span className="field-hint">A concise description of the work you want to be known for.</span></div><div className="field"><label htmlFor="summary">Career summary</label><textarea id="summary" name="summary" className="textarea" defaultValue={profile.summary} rows={6} placeholder="Your experience, strengths, and the problems you solve…" /></div><SubmitButton pendingLabel="Saving…">Save profile</SubmitButton></section></form>}<section className="form-section"><h2>Product tour</h2><p>Replay the short workspace tour to revisit navigation, capture, and command shortcuts.</p><form action={restartTour}><SubmitButton className="button secondary" pendingLabel="Starting…">Restart product tour</SubmitButton></form></section></main></div></div>;
}
